spring:
  datasource:
    url: jdbc:mysql://192.168.3.4:3306/medicine_management?characterEncoding=utf8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 5
#      idle-timeout: 30000
#      connection-timeout: 20000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sim.sys.entity
server:
  port: 8080